### ISSUE TITLE
Requesting Items

### ISSUE THREAD

**Issue by cnetz** [0ptera/Logistic-Train-Network#328]
**Error Message or Bug Description**

![whypickup](https://github.com/0ptera/Logistic-Train-Network/assets/35546187/f1fa9c43-094c-40e9-bb1b-c9bc6cb05765)

![request](https://github.com/0ptera/Logistic-Train-Network/assets/35546187/b8cc134a-b7d9-404c-b29e-55bdfa8b442f)

As seen in the second photo, this is my setup for requesting copper plates. In photo 1 it is sending a train from afasfasf to vlczero but both train stations are set to the same settings as seen in photo 2 (requesting copper). 

As for station afasfasf, it had +64000 copper plates, and as soon as it dropped to a negative number the issue stopped, and no trains were being requested from afasfasf to vlczero. Again, afasfasf is a requesting station, and not a providing station. 

Version
1.18.5

I was able to reproduce this on a new save.

I do apologize if this is not a bug but rather an error on my setup as I am not quite sure.

**Comment by 0ptera** [comment]
If no provide threshold is set LTN uses map settings (default 1000).
With 64k plates it's easy for overloaded trains to overflow a requester into becoming a provider.
