### ISSUE TITLE
requester station requesting loads of trains despite the train limit 

### ISSUE THREAD

**Issue by DrSpectacular** [0ptera/Logistic-Train-Network#329]
Im here to ask for sme help, im not sure why but my requester stations are requesting way to many trains, i even have the train limit set to two or one but i find my self with about 20 trains all trying to get into one station and its causeing a complete block.
![Screenshot 2023-12-02 224412](https://github.com/0ptera/Logistic-Train-Network/assets/70489490/c7a18649-8395-454e-8a7a-69206f8ad052)
this is how ive got the train set up, max limit of two trains with a request of about -14k, thoes storages can hold smething like 100K total
![image](https://github.com/0ptera/Logistic-Train-Network/assets/70489490/d1bd793f-8f87-46be-afea-2dfa89080615)
this is the combinator
![image](https://github.com/0ptera/Logistic-Train-Network/assets/70489490/5541e505-b8da-46cb-bafc-0299df3b7ea9)
and this is the extent of the problem, they are even waiting in the other train stops on the right.

when i set these up i whatched a video from laurence playes and was only looking for single item loading and followed how he set them up.
i also have requester trains pulling up to requester station for items aswell idk whats up with that.

plz help :(

**Comment by 0ptera** [comment]
Can't help you with the information given.

Check values feed to LTN stop input. LTN-Manager can help here.
Similar issues have been solve several times on the [LTN subforum](https://forums.factorio.com/viewforum.php?f=214) already, please search for those.
