### ISSUE TITLE
`Make_Stop_RichText` does not work for a/some/all train event(s)

### ISSUE THREAD

**Issue by Quezler** [0ptera/Logistic-Train-Network#331]
**Error message or bug description**
It looks like `from_entity` and `to_entity` are nil [here](https://github.com/0ptera/Logistic-Train-Network/blob/f4e3a14b3f657f59c296e29e8b5fec40c42f6a22/script/train-events.lua#L56), so the error message doesn't tries to compact the rich text:
![Screenshot 2024-01-28 at 13 35 19](https://github.com/0ptera/Logistic-Train-Network/assets/3179271/7da08f3a-8cc7-43f0-8652-631709ddc030)

**To Reproduce**
Return a dispatched train to the depot.

**LTN version**
1.18.5

**Comment by 0ptera** [comment]
Thanks for reporting.
Though your screenshot doesn't show the message, I was able to reproduce and fix it.

**Comment by Quezler** [comment]
it did show the message, the one at the same height as the percentage from recipe book, but thanks for fixing it. 🙂
